all:
	vivado -mode batch -source script/gen_project_and_bit.tcl

clean:
	rm -rf PynqInverceMatrix3 ../../ip_repo/PynqInverceMatrix3 \
	../../../../pynq/PynqInverceMatrix3.bit ../../../../pynq/PynqInverceMatrix3.tcl \
	vivado* *.log 
