all:
	vivado -mode batch -source script/gen_project_and_bit.tcl

clean:
	rm -rf PynqInverceMatrix2 ../../ip_repo/PynqInverceMatrix2 \
	../../../../pynq/PynqInverceMatrix2.bit ../../../../pynq/PynqInverceMatrix2.tcl \
	vivado* *.log 
